// The honest word shown on first launch, and kept available in
// Settings. Acceptance is recorded with a timestamp on this device.
import * as SecureStore from 'expo-secure-store';

const ACCEPTED_KEY = 'disclosure_accepted_v1';

export const DISCLOSURE_TITLE = 'Before we begin, an honest word.';

export const DISCLOSURE_TEXT = `Jireh is a devotional companion powered by artificial intelligence. The face you will see and the voice you will hear are crafted art — they are not Jesus Christ, not God, and make no claim of His true appearance or voice. The words are generated by AI guided by Scripture, and like anything made by human hands, they can be imperfect. Test everything against the Bible itself.

Jireh is not a church, a pastor, or a counselor, and it is not a substitute for Scripture, prayer, Christian community, or professional care. For medical, legal, financial, or mental-health needs, please seek a qualified professional. If you are in crisis, call or text 988 (United States) or your local emergency number right away.

By continuing, you confirm you understand what Jireh is — a devotional tool made with love — and agree to use it in that spirit.`;

export async function recordDisclosureAccepted(): Promise<void> {
  try {
    await SecureStore.setItemAsync(ACCEPTED_KEY, new Date().toISOString());
  } catch {
    // storage unavailable — acceptance still applies this session
  }
}

export async function getDisclosureAcceptedAt(): Promise<string | null> {
  try {
    return await SecureStore.getItemAsync(ACCEPTED_KEY);
  } catch {
    return null;
  }
}
